title: The Logic Bomb
email: sadistic.pentester@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A Pentesters Blog, This blog will be a completely khaotic list of tools, articles, and resources I use regularly in Pentesting and TryHackMe/Hacking CTF situations.
baseurl: "/lb" # the subpath of your site
url: "https://sadistic.github.io" # the base hostname & protocol for your site
#twitter_username: sadistic
#tryhackme_username: Sadistic

# Required plugins for the theme to work properly
plugins:
  - jekyll-remote-theme
  - jemoji
  - jekyll-youtube

# Including jekyll-shell-theme using the jekyll-remote-theme plugin
remote_theme: tareqdandachi/jekyll-shell-theme

sass:
  #style: compressed

highlighter: rouge #selecting the highlighter, default is rouge

header_pages:
  - index.md
  #- Discord.md
  - Tools.md
  - Blog.md
  - About.md
  - GFX-Shop.md
  
# controls how big the shell and font looks
font-size: small # options: [small] or [large]
