title: The Logic Bomb
email: sadistic.pentester@gmail.com
description: >- # This page will be a completely khaotic list of tools, articles, and resources I use regularly in Pentesting and CTF situations. My goal is to build this list as often as possible with examples, articles, and useful tips. It will serve as a reference for when I forget things and hopefully will help others to discover tools that they haven’t used.
baseurl: "/lb" # the subpath of your site
url: "https://sadistic.github.io" # the base hostname & protocol for your site
#twitter_username: sadistic
tryhackme_username: Sadistic

# Required plugins for the theme to work properly
plugins:
  - jekyll-remote-theme
  - jemoji

# Including jekyll-shell-theme using the jekyll-remote-theme plugin
remote_theme: tareqdandachi/jekyll-shell-theme

sass:
  #style: compressed

highlighter: rouge #selecting the highlighter, default is rouge

header_pages:
  - index.md
  - blog.md
  - about.md
  - read-me.md
  
# controls how big the shell and font looks
font-size: small # options: [small] or [large]
